DefaultContentLanguage = "en"
title = "Notebook | CyrusN"
theme = "notebook-searcher"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
paginate = 10
# baseURL = "http://example.org/"
# disqusShortname = "your-disqus-short-name"

# # Enable GitInfo feature
# # Get the last Git revision information for every content file.
# # The date of "Last Modified" can be fetched from Git
# # [Git Info Variables | Hugo](https://gohugo.io/variables/git/#lastmod)
# enableGitInfo = true

[blackfriday]
  hrefTargetBlank = true

[Params]
  subtitle = "My Notes"
  dateFormat = "2006-01-02"
  # logo = "img/avatar.png"
  # favicon = "favicon.ico"

[Author]
  name = "Author"
  email = "author@example.com"

[[menu.main]]
    name = "Note"
    identifier = "note"
    url = "/note/"
    weight = 2

[[menu.main]]
    name = "Post"
    identifier = "post"
    url = "/post/"
    weight = 3

[[menu.main]]
    name = "Slide"
    identifier = "slide"
    url = "/slide/"
    weight = 5

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 10

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON"]
